### ISSUE TITLE
Not compliant for install via HACS

### ISSUE THREAD

**Issue by bellringer2** [gpbenton/freesat_control#6]
Hi,

I'd really like to give this a try but the only way I know (very much a HA newbie) to install on HA is via HACS.

On trying this I get this error "Repostitory structure for master is not compliant"

Maybe it was never intended to be installed via HACS or perhaps I'm at fault.

Any advice very welcome.
Thanks

**Comment by gpbenton** [comment]
This is a python script to control a freesat tv box, nothing more.  It is not intended to be used directly with HA, although anyone can use it to create something they need.

I use the script as part of an App with appdaemon, but I have not published that, and  I do not intend to.
